services:
  app:
    build: .
    container_name: template-app
    ports:
      - 8083:8083
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postqreSQL:5432/template
    depends_on:
      postqreSQL:
        condition: service_healthy
    networks: [app-net]

  postqreSQL:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: postqreSQL
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [app-net]

networks:
  app-net:
    driver: bridge

volumes:
  postgres-data:
