server:
  port: 8080
spring:
  application:
    name: template
  datasource:
    url: jdbc:postgresql://localhost:5432/sportclub
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  metrics:
    export:
      prometheus:
       enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true