CREATE TABLE token_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_token VARCHAR(255) NOT NULL,
    refresh_token VARCHAR(255) NOT NULL,
    loggedOut BOOLEAN,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users_table(id)
);